// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function QueryPlaceBind(arg1:string):Promise<entities.QueryPlaceApiResponse>;

export function QueryWheatherBind(arg1:number,arg2:number):Promise<entities.WheatherQueryApiResponse>;
