// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryPlaceBind(arg1) {
  return window['go']['main']['WheeaApp']['QueryPlaceBind'](arg1);
}

export function QueryWheatherBind(arg1, arg2) {
  return window['go']['main']['WheeaApp']['QueryWheatherBind'](arg1, arg2);
}
